# Generated by Django 3.0.6 on 2020-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200527_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
